name: Apply Patch
on: [workflow_dispatch]
jobs:
  apply-patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -L https://github.com/dey-uname/glsl/blob/main/ppsspp_glsl.patch | git apply
          git add .
          git commit -m "Applied patch glsl cache"
